controller_list:
  - name: /mhuman/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - jright_shoulder
      - jright_upper_arm
      - jright_forearm
    gains:
      jright_shoulder:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1
      jright_upper_arm:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1   
      jright_forearm:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1   
  - name: /mhuman/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - jright_wrist
      - jright_grip_rhand
    gains:
      jright_wrist:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1
      jright_grip_rhand:
        p: 100
        i: 0.01
        d: 10
        i_clamp: 1
         

