controller_list:
  - name: fake_right_arm_controller
    joints:
      - jright_shoulder
      - jright_upper_arm
      - jright_forearm
  - name: fake_right_hand_controller
    joints:
      - jright_wrist
      - jright_grip_rhand