mhuman:
# MoveIt-specific simulation settings
#  moveit_sim_hw_interface:
#    joint_model_group: controllers_initial_group_
#    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
#  generic_hw_control_loop:
#    loop_hz: 300
#    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
#  hardware_interface:
#    joints:
#      - jright_shoulder
#      - jright_upper_arm
#      - jright_forearm
#      - jright_wrist
#      - jright_grip_rhand
#    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - jright_shoulder
      - jright_upper_arm
      - jright_forearm
  gains:
    jright_shoulder: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
    jright_upper_arm: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
    jright_forearm: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}

  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - jright_wrist
      - jright_grip_rhand
  gains:  
    jright_wrist: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
    jright_grip_rhand: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}

controller_list:
  - name: mhuman/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - jright_shoulder
      - jright_upper_arm
      - jright_forearm 
  gains:
    jright_shoulder: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
    jright_upper_arm: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
    jright_forearm: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}

  - name: mhuman/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - jright_wrist
      - jright_grip_rhand
  gains:  
    jright_wrist: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
    jright_grip_rhand: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}

